### PR TITLE
[sailfish-browser] Drop Privileged permission from application. JB#54275 OMP#JOLLA-143

### PR DESCRIPTION
**Pull request by blammit**

### CODE REVIEW

**Comment by blammit** [comment]
@rainemak does Privileged also need to be removed from sailfish-captiveportal.desktop?

**Review by okodron — APPROVED** [review]

**Comment by rainemak** [comment]
> @rainemak does Privileged also need to be removed from sailfish-captiveportal.desktop?

Yes, there should be no need for Privileged in the sailfish-captiveportal.desktop.

**Comment by blammit** [comment]
> > @rainemak does Privileged also need to be removed from sailfish-captiveportal.desktop?
> 
> Yes, there should be no need for Privileged in the sailfish-captiveportal.desktop.

Thanks, updated.

**Review by rainemak — APPROVED** [review]

**Comment by rainemak** [comment]
Rebased

**Pull request merged**
