### PR TITLE
Throttle setting of bottom margin

### PR DESCRIPTION
**Pull request by rainemak**

### CODE REVIEW

**Comment by rainemak** [comment]
This should fix also https://github.com/sailfishos/sailfish-browser/issues/563

@pvuorela maybe you'd like to take this to test ride? See the other commit that this fixes.

**Comment by rainemak** [comment]
Not there yet. Needs something more.

**Comment by pvuorela** [comment]
Already better, but...

- Facebook chat open, click on message field -> gets focus, keyboard appears on top of the field (no change here).
- Scroll page to have field visible and then swipe keyboard away -> keyboard sized margin stays on the screen. Sometimes it works, though, and if keyboard swipe is changed to clicking the page outside the message field it works ok too.

**Comment by rainemak** [comment]
Scrolling input to visible region needs some fixes, especially textarea handling.

That's good finding that keyboard sized margins stays on the screen. Will check, thanks!

**Comment by rainemak** [comment]
Updated. Split updateViewMargins into two. updateViewMargins is guarded and called similarly as it used to be, resetViewMargins resets view margins as per content height. When vkb is closed, resetViewMargins is called directly.

**Comment by pvuorela** [comment]
Swipe issue now fixed, yay. LGTM with i-don't-really-now-browser-well disclaimer. But changes seem sane.

**Pull request merged**
