### PR TITLE
Do not start margin change throttle without content

### PR DESCRIPTION
**Pull request by rainemak**

### CODE REVIEW

**Comment by chriadam** [comment]
What happens if contentHeight bounces between some value and zero, repeatedly?

**Comment by rainemak** [comment]
Zeros would be ignored. However, that's not a normal case as when frame metrics starts appearing we do have content <= something to render as well. Normal bouncing case is between less than screenful of content and multiple screenfuls of content.

**Comment by chriadam** [comment]
And in that case, the throttle would still apply.  Cool.  LGTM

**Comment by rainemak** [comment]
Yes, it would still apply. Will merge.

**Pull request merged**
