### PR TITLE
Revoke geolocation permissions upon app restart. 

### PR DESCRIPTION
**Pull request by rojkov**
Keep accepted/reject hosts in a hash instead of single values for accepted and rejected urls.

### CODE REVIEW

**Comment by tworaz** [comment]
The patch LGTM. I just wonder if we plan to include it in 1.1.9 release. If so I don't know if we can change any translations.

**Comment by rainemak** [comment]
Translation deadline has passed so as is this cannot be picked to 1.1.9. I don't think that this is a 1.1.9 blocker per se but would be good addition. Will check if this would be accepted still without the translation change.

**Comment by rojkov** [comment]
The spec requires to show host name in UI. Without the UI change it's safer to eagerly revoke the permission thus I wouldn't take it to 1.1.9

**Comment by rainemak** [comment]
@rojkov I agree, eager revoke is safe for 1.1.9.

**Comment by rainemak** [comment]
LGTM

**Pull request merged**
