### PR TITLE
[browser] Fix active tab display when opening tabs. Fixes JB#54794 OMP#JOLLA-214

### PR DESCRIPTION
**Pull request by xlise**

### CODE REVIEW

**Comment by adenexter** [comment]
Ideally you'd change the highlightRangeMode so the GridView would scroll itself to keep the current item in view, but I can't find a combination of parameters that doesn't also change the scroll limits.

**Review by adenexter — APPROVED** [review]

**Review by aroditelev — APPROVED** [review]

**Comment by rainemak** [comment]
@xlise could you rebase this one?

**Comment by xlise** [comment]
> @xlise could you rebase this one?

rebased

**Comment by xlise** [comment]
> Ideally you'd change the highlightRangeMode so the GridView would scroll itself to keep the current item in view, but I can't find a combination of parameters that doesn't also change the scroll limits.

Thanks for the advice

**Pull request merged**
