### PR TITLE
[user-agent] User agent override for skype.com. Fixes JB#54785

### PR DESCRIPTION
**Pull request by paveltkv**

### CODE REVIEW

**Comment by CaptainKhan** [comment]
STOP

UNSUBSCRIBE

**Review by okodron — APPROVED** [review]

**Comment by rainemak** [comment]
Please rebase

**Review by rainemak — APPROVED** [review]

**Comment by rainemak** [comment]
CC @jpwalden

**Comment by paveltkv** [comment]
rebased

**Review by rainemak — APPROVED** [review]

**Comment by paveltkv** [comment]
rebased

**Pull request merged**
