### PR TITLE
Add RemovableMedia Sailjail permission

### PR DESCRIPTION
**Pull request by LaakkonenJussi**
Allow browser to access documents on removable, external data storages
such as USB sticks and SD cards.

### CODE REVIEW

**Comment by LaakkonenJussi** [comment]
@okodron could you review as well?

**Comment by okodron** [comment]
> @okodron could you review as well?

Jussi, it looks like there is a small copy-paste issue in commit message as it's not about the office application :)

**Comment by LaakkonenJussi** [comment]
@okodron Indeed there is! Thanks for spotting it out.

**Comment by LaakkonenJussi** [comment]
Fixed the typo, @Tomin1 @rainemak @okodron waiting for approval.

**Review by Tomin1 — APPROVED** [review]

**Review by okodron — APPROVED** [review]

**Pull request merged**
