### PR TITLE
[browser] Do not force chrome to visible when page loaded. JB#50422

### PR DESCRIPTION
**Pull request by rainemak**

### CODE REVIEW

**Comment by rainemak** [comment]
@llewelld could you give a look to this? This would alleviate the problem a bit. Without this toolbar is not lowered by panning the content if the content length is right (on clean browser opening https://techcrunch.com). Opening and closing the overlay can be used to workaround the issue.

**Comment by rainemak** [comment]
This is not about padding or margin. It's just that toolbar cannot go away when page loaded and contentheight is "correct".
To be noted that padding doesn't help either on some problematic pages.

**Comment by llewelld** [comment]
> This is not about padding or margin. It's just that toolbar cannot go away when page loaded and contentheight is "correct".

Ah, yes, I don't think we're in disagreement here. I simply meant that this is a nicer solution than the equivalent one we used for email (which was to add additional padding to the email to allow it to scroll).

**Comment by rainemak** [comment]
There's still that extra margin in place if the content length short enough.

**Comment by rainemak** [comment]
Yes @llewelld we're not disagreeing :+1:

**Pull request merged**
