### PR TITLE
[browser-settings] Show tap to install for search engines that user can install. JB#40380

### PR DESCRIPTION
**Pull request by rainemak**

### CODE REVIEW

**Comment by rainemak** [comment]
Will rebase this after https://github.com/sailfishos/sailfish-browser/pull/787

**Comment by rainemak** [comment]
Rebased

**Comment by rainemak** [comment]
Added two commits
1. That fixes indentations from the SettingsPage
2. Then another commit that fixes one comparison operator

**Review by mkenttala — APPROVED** [review]
LGTM

**Pull request merged**
