### PR TITLE
[sailfish-browser] Use remorse delete for favorites. JB#48357

### PR DESCRIPTION
**Pull request by rainemak**
This commit also removes obsoleted animated removal call.

### CODE REVIEW

**Comment by rainemak** [comment]
@jpetrell review ?

**Comment by jpetrell** [comment]
I don't see "Deleted" label on so small remorse item. Remorse within grid item works with large grid items like we have in Notes and Gallery, but for smaller grid items like what you see in Media playlist grid, Browser and People favorites, we normally show the remorse below the row as a separate, wider item. I will try to extend GridItem to cover that case implicitly in Silica side, if that works the change here should then work too.

**Comment by rainemak** [comment]
Rebased this one. @jpetrell do you have comments?

**Comment by jpetrell** [comment]
No looks good. 👍 Sorry tested this earlier, but forgot to write LGTM.

**Pull request merged**
