### PR TITLE
[browser] Open start page when tab count reaches zero. Fixes JB#54408 OMP#JOLLA-162

### PR DESCRIPTION
**Pull request by rainemak**
Requires https://github.com/sailfishos/sailjail-permissions/pull/81

### CODE REVIEW

**Review by okodron — APPROVED** [review]

**Comment by rainemak** [comment]
Rebased

**Review by Tomin1 — APPROVED** [review]
LGTM, although I could use a little bit of explanation why exactly this helps. :)

**Review by atatarov — APPROVED** [review]

**Comment by rainemak** [comment]
@Tomin1: When tap count reaches zero, activate enteringNewTabUrl
to prevent page status updates changing overlay state. Amended the commit message as well.

**Comment by rainemak** [comment]
Rebased

**Pull request merged**
