### PR TITLE
Hook history list items up with the load signal

### PR DESCRIPTION
**Pull request by llewelld**
Hooks up the load signal from the history list items to the toolbar load signal, so that when the history list is opened from the popup menu, items selected in the history list load in the current tab.

Also removes the secondary tool bar page as it's not used any more.

### CODE REVIEW

**Comment by aroditelev** [comment]
LGTM

**Review by rainemak — APPROVED** [review]
LGTM

**Comment by rainemak** [comment]
Rebase before merging.

**Comment by rainemak** [comment]
@aroditelev, would be good if you'd do explicit approval via "Files changes" -> "Review changes"

**Comment by rainemak** [comment]
Ah, commit message is missing JOLLA-195 ref.

**Comment by llewelld** [comment]
Rebased and fixed the commit ref. Thanks for spotting it.

**Review by aroditelev — APPROVED** [review]

**Review by aroditelev — APPROVED** [review]

**Review by aroditelev — APPROVED** [review]

**Review by aroditelev — APPROVED** [review]

**Pull request merged**
