### PR TITLE
Add a page for testing the bottom margin changes

### PR DESCRIPTION
**Pull request by llewelld**
Also adds a redirect from index.html to the contents listing, because I can never remember the correct name of the page.

There's a test version of the test page here: https://www.flypig.co.uk/tests/bottom-margin.html

Thanks Pavel for the nice input on this.

### CODE REVIEW

**Review by paveltkv — APPROVED** [review]

**Comment by llewelld** [comment]
The last change added `vertical-align: bottom;` to `button { ... }` as suggested by Pavel to ensure the buttons are positioned correctly.

**Review by okodron — APPROVED** [review]

**Review by rainemak — APPROVED** [review]
LGTM

**Comment by rainemak** [comment]
Rebase and merge

**Comment by llewelld** [comment]
Rebased, and thanks for the prod.

**Pull request merged**
