### PR TITLE
[sailfish-browser] Add fallback timer for orientation fader. Contributes to JB#36210

### PR DESCRIPTION
**Pull request by rainemak**

### CODE REVIEW

**Comment by rainemak** [comment]
@pvuorela , @chriadam , @siteshwar , @mkosola review ?

**Comment by mkosola** [comment]
Interval could be maybe a bit longer, otherwise LGTM

**Comment by rainemak** [comment]
Increased the timeout to 3500ms.

**Comment by rainemak** [comment]
@mkosola @pvuorela have you seen sticky orientation faders?

After better fix went in [1], I have not seen this happening.

[1]
https://git.merproject.org/mer-core/embedlite-components/merge_requests/26

**Comment by mkosola** [comment]
I have had no issues with this after fix

**Comment by pvuorela** [comment]
The content staying white etc? Yes, I've still had that a few times.

**Comment by rainemak** [comment]
While being quite oldie wondering if @pvuorela has still seen this?

**Comment by pvuorela** [comment]
Hm, not sure. Perhaps not.

**Comment by rainemak** [comment]
Ok, will close this then. Simple to recreate if needed.

**Pull request closed without merging**
