### PR TITLE
[sailfish-browser] Rebase text selection feature to latest master

### PR DESCRIPTION
**Pull request by CODeRUS**
Comparing to the previous PR (https://github.com/sailfishos/sailfish-
browser/pull/129) here
1. merge conflicts resolved

### CODE REVIEW

**Comment by roppola** [comment]
Sorry for the late response, I had a tried out the text selection last friday. it's definitely a great start, thanks for contributing.

Any ideas how to bring it closer to silica text selection experience? Automatic copying on selection change, zooming in and vertically offsetting the content to prevent finger occlusion.

**Comment by CODeRUS** [comment]
Automatic copying is no problem. Other features should be checked.

**Comment by roppola** [comment]
Excellent, let me know if there's any details/assets missing.

**Comment by rainemak** [comment]
Rebased and fixed this over here: https://github.com/sailfishos/sailfish-browser/pull/534. Small adjustments still needed.

**Pull request closed without merging**
